apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-mart-dev

resources:
  - ../../base

labels:
  - pairs:
      environment: development

# Development-specific patches
patches:
  - path: replica-patch.yaml
  - path: resource-patch.yaml

configMapGenerator:
  - name: shopping-mart-config
    behavior: merge
    literals:
      - DEBUG=True
      - VITE_API_BASE_URL=http://localhost:8000/api/v1

images:
  - name: shopping-mart-backend
    newTag: dev-latest
  - name: shopping-mart-frontend
    newTag: dev-latest
