apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-mart-dev

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: development

# Development-specific patches
patches:
  - path: replica-patch.yaml
  - path: resource-patch.yaml
  - path: configmap-patch.yaml

images:
  - name: shopping-mart-backend
    newTag: dev-latest
  - name: shopping-mart-frontend
    newTag: dev-latest
